Header header
float64 m_lat       # in degree
float64 m_longt     # in degree
float32 m_height
float32 m_x    # local pos x from take off
float32 m_y    # local pos y from take off
float32 m_z    # local pos z from take off
float32 m_heading   # heading is in [-180,180]
float32 m_roll
float32 m_pitch


###comments###
# m_lat: current drone latitude in degree
# m_longt: current drone longtitude in degree
# m_height: current drone height
# m_x: e current drone in local frame of x axis
# m_y: n current drone in local frame of y axis
# m_z: u current drone in local frame of z axis
# m_heading current drone heading
# NED ne(-u) heading
# ENU enu -heading
######